name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main     # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your code
      - uses: actions/checkout@v3

      # 2) Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install deps
      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      # 4) Write .env from Secrets
      - name: Create .env
        run: |
          cat <<EOF > ./client/.env
          REACT_APP_GOOGLE_API_KEY=${{ secrets.REACT_APP_GOOGLE_API_KEY }}
          REACT_APP_OTHER_SECRET=${{ secrets.OTHER_SECRET }}
          EOF

      # 5) Build & Deploy
      - name: Build and Deploy
        run: |
          npm run build
          npx gh-pages -d build
        working-directory: ./client

      # 6) Cleanup (optional) – remove the generated .env
      - name: Remove .env
        run: rm ./client/.env