name: Weekly Course Fetch
on:
  schedule:
    - cron: '0 0 * * 1'  # every Monday UTC

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      UW_API_KEY:             ${{ secrets.UW_API_KEY }}
      GOOGLE_API_KEY:         ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - name: Trigger fetchCourses endpoint
        run: |
          curl -X POST https://my-app.vercel.app/api/fetchCourses \
            -H "Authorization: Bearer $SUPABASE_SERVICE_KEY" \
            -H "x-uw-api-key: $UW_API_KEY" \
            -H "x-google-api-key: $GOOGLE_API_KEY"
