name: Weekly Course Fetch

on:
  schedule:
    # Every Sunday at 3:00 UTC
    - cron: "0 3 * * 0"

jobs:
  fetch-and-upsert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Server Dependencies
        working-directory: server
        run: npm ci

      - name: Fetch & Upsert Courses
        working-directory: server
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          WATERLOO_API_KEY: ${{ secrets.WATERLOO_API_KEY }}
        run: node fetchCourses.js
