name: Fetch & Upsert Courses

on:
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 03:00 UTC
  workflow_dispatch: # manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Fetcher Dependencies
        working-directory: server
        run: npm ci

      - name: Fetch & Upsert to Supabase
        working-directory: server
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          WATERLOO_API_KEY: ${{ secrets.WATERLOO_API_KEY }}
        run: npm run fetch
